version: '3'
services:
  game-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: game-server-db
      PROD: 1
  game-server-db:
    image: mongo:4.2.0-bionic
    ports:
      - "27017:27017"
