version: '3'
services:
  game-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongo
    networks:
      - taurus-network
  mongo:
    image: mongo:4.2.0-bionic
    ports:
      - "27018:27018"
    networks:
      - taurus-network

networks:
  taurus-network:
    external: true
