FROM golang as builder

COPY ./ /go/src/github.com/coff33un/game-server-ms

WORKDIR /go/src/github.com/coff33un/game-server-ms

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /go/src/github.com/coff33un/game-server-ms/main .

CMD ["./main"]
